dist: xenial

sudo: required

language: python

python:
  - "3.7"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

install:
  - whoami
  - pwd
  - chmod go-rwx ~/.ssh/
  - ssh-keygen  -t rsa -N '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub  >> ~/.ssh/authorized_keys
  - pip install cloudmesh-installer
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
  - ls
  - pwd
  - python --version
  - mkdir -p ~/.cloudmesh
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-common/master/cloudmesh/etc/cloudmesh.yaml
  - wget -P ~/.cloudmesh https://raw.githubusercontent.com/cloudmesh/cloudmesh-cloud/master/cloudmesh/etc/cloudmesh4.yaml


script:
  - pytest -v --capture=no tests/0_basic/test_cloud_installer.py
  - pytest -v --capture=no tests/0_basic/test_host.py
